//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaReporter.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaReporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new request.
        /// </summary>
        public static string AddNewButtonTooltip {
            get {
                return ResourceManager.GetString("AddNewButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new folder.
        /// </summary>
        public static string AddNewFolder {
            get {
                return ResourceManager.GetString("AddNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new folder.
        /// </summary>
        public static string AddNewFolderButtonTooltip {
            get {
                return ResourceManager.GetString("AddNewFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clone request.
        /// </summary>
        public static string CloneButtonTooltip {
            get {
                return ResourceManager.GetString("CloneButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clone folder.
        /// </summary>
        public static string CloneFolder {
            get {
                return ResourceManager.GetString("CloneFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clone folder.
        /// </summary>
        public static string CloneFolderButtonTooltip {
            get {
                return ResourceManager.GetString("CloneFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supported only followed extensions: {0}.
        /// </summary>
        public static string DataTableSaveAsArgumentException {
            get {
                return ResourceManager.GetString("DataTableSaveAsArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на desample:.
        /// </summary>
        public static string DesampleLabel {
            get {
                return ResourceManager.GetString("DesampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle this to reduce data sampling..
        /// </summary>
        public static string DesampleTooltip {
            get {
                return ResourceManager.GetString("DesampleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dimensions:.
        /// </summary>
        public static string DimensionsLabel {
            get {
                return ResourceManager.GetString("DimensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A list of comma-separated dimensions for your Analytics data, for example: ga:medium,ga:source..
        /// </summary>
        public static string DimensionsTooltip {
            get {
                return ResourceManager.GetString("DimensionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на end-date:.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End date for fetching Analytics data. Request can specify an end date formatted as YYYY-MM-DD, or as a relative date (e.g., today, yesterday, or NdaysAgo where N is a positive integer)..
        /// </summary>
        public static string EndDateTooltip {
            get {
                return ResourceManager.GetString("EndDateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на file:.
        /// </summary>
        public static string FileNameLabel {
            get {
                return ResourceManager.GetString("FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supported file extensions: *.xlsx, *.xml, *.json..
        /// </summary>
        public static string FileNameTooltip {
            get {
                return ResourceManager.GetString("FileNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filters:.
        /// </summary>
        public static string FiltersLabel {
            get {
                return ResourceManager.GetString("FiltersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dimension or metric filters that restrict the data returned for your request..
        /// </summary>
        public static string FiltersTooltip {
            get {
                return ResourceManager.GetString("FiltersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show folders details.
        /// </summary>
        public static string FolderDetails {
            get {
                return ResourceManager.GetString("FolderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FOLDERS.
        /// </summary>
        public static string FoldersPage {
            get {
                return ResourceManager.GetString("FoldersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders - {0}.
        /// </summary>
        public static string FoldersTitle {
            get {
                return ResourceManager.GetString("FoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на max-results:.
        /// </summary>
        public static string MaxResultsLabel {
            get {
                return ResourceManager.GetString("MaxResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum number of rows to include in the response. 1 000 if empty, up to 1 048 575 in Excel and no limit in all other output formats..
        /// </summary>
        public static string MaxResultsTooltip {
            get {
                return ResourceManager.GetString("MaxResultsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на metrics:.
        /// </summary>
        public static string MetricsLabel {
            get {
                return ResourceManager.GetString("MetricsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A list of comma-separated metrics, such as ga:sessions,ga:bounces..
        /// </summary>
        public static string MetricsTooltip {
            get {
                return ResourceManager.GetString("MetricsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string OpenBigButtonText {
            get {
                return ResourceManager.GetString("OpenBigButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string OpenBigButtonTooltip {
            get {
                return ResourceManager.GetString("OpenBigButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string OpenButtonTooltip {
            get {
                return ResourceManager.GetString("OpenButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open document.
        /// </summary>
        public static string OpenDocumentButtonTooltip {
            get {
                return ResourceManager.GetString("OpenDocumentButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Email Address:.
        /// </summary>
        public static string OptionsAccountEmailAddressLabel {
            get {
                return ResourceManager.GetString("OptionsAccountEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email Address from Google Analytics account..
        /// </summary>
        public static string OptionsAccountEmailAddressLabelTooltip {
            get {
                return ResourceManager.GetString("OptionsAccountEmailAddressLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string OptionsButtonTooltip {
            get {
                return ResourceManager.GetString("OptionsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IDs:.
        /// </summary>
        public static string OptionsIDsLabel {
            get {
                return ResourceManager.GetString("OptionsIDsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IDs from Google Analytics account..
        /// </summary>
        public static string OptionsIDsLabelTooltip {
            get {
                return ResourceManager.GetString("OptionsIDsLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key Path:.
        /// </summary>
        public static string OptionsKeyPathLabel {
            get {
                return ResourceManager.GetString("OptionsKeyPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full path to file with *.p12 extension recieved from Google Analytics account..
        /// </summary>
        public static string OptionsKeyPathLabelTooltip {
            get {
                return ResourceManager.GetString("OptionsKeyPathLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OptionsOKButtonText {
            get {
                return ResourceManager.GetString("OptionsOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options - {0}.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PROJECT.
        /// </summary>
        public static string ProjectPage {
            get {
                return ResourceManager.GetString("ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute request.
        /// </summary>
        public static string RefreshBigButtonText {
            get {
                return ResourceManager.GetString("RefreshBigButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute request.
        /// </summary>
        public static string RefreshBigButtonTooltip {
            get {
                return ResourceManager.GetString("RefreshBigButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute request.
        /// </summary>
        public static string RefreshButtonTooltip {
            get {
                return ResourceManager.GetString("RefreshButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There has been an error processing your request.
        /// </summary>
        public static string RefreshErrorMessage {
            get {
                return ResourceManager.GetString("RefreshErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute all.
        /// </summary>
        public static string RefreshFolderBigButtonText {
            get {
                return ResourceManager.GetString("RefreshFolderBigButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute all requests in folder.
        /// </summary>
        public static string RefreshFolderBigButtonTooltip {
            get {
                return ResourceManager.GetString("RefreshFolderBigButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute all requests in folder.
        /// </summary>
        public static string RefreshFolderButtonTooltip {
            get {
                return ResourceManager.GetString("RefreshFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request.
        /// </summary>
        public static string RefreshSuccessMessage0 {
            get {
                return ResourceManager.GetString("RefreshSuccessMessage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на processed successfully.
        /// </summary>
        public static string RefreshSuccessMessage1 {
            get {
                return ResourceManager.GetString("RefreshSuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discard all changes.
        /// </summary>
        public static string ReloadButtonTooltip {
            get {
                return ResourceManager.GetString("ReloadButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove request.
        /// </summary>
        public static string RemoveButtonTooltip {
            get {
                return ResourceManager.GetString("RemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove folder.
        /// </summary>
        public static string RemoveFolder {
            get {
                return ResourceManager.GetString("RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove folder.
        /// </summary>
        public static string RemoveFolderButtonTooltip {
            get {
                return ResourceManager.GetString("RemoveFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REQUESTS.
        /// </summary>
        public static string RequestsPage {
            get {
                return ResourceManager.GetString("RequestsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run all folders requests.
        /// </summary>
        public static string RunFolder {
            get {
                return ResourceManager.GetString("RunFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as....
        /// </summary>
        public static string SaveAsButtonTooltip {
            get {
                return ResourceManager.GetString("SaveAsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string SaveButtonTooltip {
            get {
                return ResourceManager.GetString("SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not saved. Try again?.
        /// </summary>
        public static string SaveErrorMessage {
            get {
                return ResourceManager.GetString("SaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на segment:.
        /// </summary>
        public static string SegmentLabel {
            get {
                return ResourceManager.GetString("SegmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Segments the data returned for your request..
        /// </summary>
        public static string SegmentTooltip {
            get {
                return ResourceManager.GetString("SegmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sort:.
        /// </summary>
        public static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A list of comma-separated dimensions and metrics indicating the sorting order and sorting direction for the returned data..
        /// </summary>
        public static string SortTooltip {
            get {
                return ResourceManager.GetString("SortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на start-date:.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start date for fetching Analytics data. Requests can specify a start date formatted as YYYY-MM-DD, or as a relative date (e.g., today, yesterday, or NdaysAgo where N is a positive integer)..
        /// </summary>
        public static string StartDateTooltip {
            get {
                return ResourceManager.GetString("StartDateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title. Used as a worksheet name in export to Excel..
        /// </summary>
        public static string TitleTooltip {
            get {
                return ResourceManager.GetString("TitleTooltip", resourceCulture);
            }
        }
    }
}
